server:
  port: 8101
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_alibaba_shop
    hikari:
      username: root
      password: root
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver